Document: mikumikupenguin
Title: Debian mikumikupenguin Manual
Author: <insert document author here>
Abstract: This manual describes what mikumikupenguin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mikumikupenguin/mikumikupenguin.sgml.gz

Format: postscript
Files: /usr/share/doc/mikumikupenguin/mikumikupenguin.ps.gz

Format: text
Files: /usr/share/doc/mikumikupenguin/mikumikupenguin.text.gz

Format: HTML
Index: /usr/share/doc/mikumikupenguin/html/index.html
Files: /usr/share/doc/mikumikupenguin/html/*.html
